export const HIDE_ELEMENT = 'HIDE_ELEMENT'
export const SHOW_ELEMENT = 'SHOW_ELEMENT'
export const LOG_OUT = 'LOG_OUT'
export const LOG_IN = 'LOG_IN'
export const SELECT_LOCATION = 'SELECT_LOCATION'
export const FETCH_DATA_PERSONS = 'FETCH_DATA_PERSONS'
export const ADD_PERSONS = 'ADD_PERSONS'